export const SHOW_TASKS = "SHOW_TASK"
export const ADD_TASK = "ADD_TASK"
export const REMOVE = "REMOVE"
export const SET_TITLE = "SET_TITLE"
export const SET_BODY = "SET_BODY"
export const SET_ERROR = "SET_ERROR"
