export const ADD_TODO = "ADD_TODO"
export const ADD_DESCRIPTION = "ADD_DESCRIPTION"
export const REMOVE_TODO = "REMOVE_TODO"
export const TODO_TITLE = "TODO_TITLE"
export const SHOW_TODO = "SHOW_TODO"
export const SET_ERROR = "SET_ERROR"